namespace: cankush625

name: multicloudkubernetescluster

version: 1.0.0

readme: README.md

authors:
- Ankush Chavan <cankush625@gmail.com>


description: This collection contains the roles for configuring multi-cloud kubernetes master and slave nodes

license_file: LICENSE

tags: 
- kubernetes
- k8s
- kubernetescluster
- k8scluster
- cluster
- multinode
- multicloud
- automation

dependencies: {}

repository: https://github.com/cankush625/multicloudkubernetescluster

documentation: http://docs.example.com

homepage: http://example.com

issues: https://github.com/cankush625/multicloudkubernetescluster
